/** Голоса Gemini Live API (prebuiltVoiceConfig). Имя = voice_name для API. */
export enum GeminiVoice {
  Zephyr = "Zephyr",
  Kore = "Kore",
  Orus = "Orus",
  Autonoe = "Autonoe",
  Umbriel = "Umbriel",
  Erinome = "Erinome",
  Laomedeia = "Laomedeia",
  Schedar = "Schedar",
  Achird = "Achird",
  Sadachbia = "Sadachbia",
  Puck = "Puck",
  Fenrir = "Fenrir",
  Aoede = "Aoede",
  Enceladus = "Enceladus",
  Algieba = "Algieba",
  Algenib = "Algenib",
  Achernar = "Achernar",
  Gacrux = "Gacrux",
  Zubenelgenubi = "Zubenelgenubi",
  Sadaltager = "Sadaltager",
  Charon = "Charon",
  Leda = "Leda",
  Callirrhoe = "Callirrhoe",
  Iapetus = "Iapetus",
  Despina = "Despina",
  Rasalgethi = "Rasalgethi",
  Alnilam = "Alnilam",
  Pulcherrima = "Pulcherrima",
  Vindemiatrix = "Vindemiatrix",
  Sulafat = "Sulafat",
}

/** Подписи голосов по языкам (для UI). */
export type GeminiVoiceOption = { value: GeminiVoice; labelEn: string; labelRu: string };

export const GEMINI_VOICES: GeminiVoiceOption[] = [
  { value: GeminiVoice.Zephyr, labelEn: "Zephyr — Bright", labelRu: "Zephyr — Яркий" },
  { value: GeminiVoice.Kore, labelEn: "Kore — Firm", labelRu: "Kore — Твёрдый" },
  { value: GeminiVoice.Orus, labelEn: "Orus — Firm", labelRu: "Orus — Твёрдый" },
  { value: GeminiVoice.Autonoe, labelEn: "Autonoe — Bright", labelRu: "Autonoe — Яркий" },
  { value: GeminiVoice.Umbriel, labelEn: "Umbriel — Easy-going", labelRu: "Umbriel — Раскованный" },
  { value: GeminiVoice.Erinome, labelEn: "Erinome — Clear", labelRu: "Erinome — Чёткий" },
  { value: GeminiVoice.Laomedeia, labelEn: "Laomedeia — Upbeat", labelRu: "Laomedeia — Бодрый" },
  { value: GeminiVoice.Schedar, labelEn: "Schedar — Even", labelRu: "Schedar — Ровный" },
  { value: GeminiVoice.Achird, labelEn: "Achird — Friendly", labelRu: "Achird — Дружелюбный" },
  { value: GeminiVoice.Sadachbia, labelEn: "Sadachbia — Lively", labelRu: "Sadachbia — Живой" },
  { value: GeminiVoice.Puck, labelEn: "Puck — Upbeat", labelRu: "Puck — Бодрый" },
  { value: GeminiVoice.Fenrir, labelEn: "Fenrir — Excitable", labelRu: "Fenrir — Впечатлительный" },
  { value: GeminiVoice.Aoede, labelEn: "Aoede — Breezy", labelRu: "Aoede — Лёгкий" },
  { value: GeminiVoice.Enceladus, labelEn: "Enceladus — Breathy", labelRu: "Enceladus — Дыхательный" },
  { value: GeminiVoice.Algieba, labelEn: "Algieba — Smooth", labelRu: "Algieba — Плавный" },
  { value: GeminiVoice.Algenib, labelEn: "Algenib — Gravelly", labelRu: "Algenib — Хриплый" },
  { value: GeminiVoice.Achernar, labelEn: "Achernar — Soft", labelRu: "Achernar — Мягкий" },
  { value: GeminiVoice.Gacrux, labelEn: "Gacrux — Mature", labelRu: "Gacrux — Зрелый" },
  { value: GeminiVoice.Zubenelgenubi, labelEn: "Zubenelgenubi — Casual", labelRu: "Zubenelgenubi — Непринуждённый" },
  { value: GeminiVoice.Sadaltager, labelEn: "Sadaltager — Knowledgeable", labelRu: "Sadaltager — Осведомлённый" },
  { value: GeminiVoice.Charon, labelEn: "Charon — Informative", labelRu: "Charon — Информативный" },
  { value: GeminiVoice.Leda, labelEn: "Leda — Youthful", labelRu: "Leda — Молодой" },
  { value: GeminiVoice.Callirrhoe, labelEn: "Callirrhoe — Easy-going", labelRu: "Callirrhoe — Раскованный" },
  { value: GeminiVoice.Iapetus, labelEn: "Iapetus — Clear", labelRu: "Iapetus — Чёткий" },
  { value: GeminiVoice.Despina, labelEn: "Despina — Smooth", labelRu: "Despina — Плавный" },
  { value: GeminiVoice.Rasalgethi, labelEn: "Rasalgethi — Informative", labelRu: "Rasalgethi — Информативный" },
  { value: GeminiVoice.Alnilam, labelEn: "Alnilam — Firm", labelRu: "Alnilam — Твёрдый" },
  { value: GeminiVoice.Pulcherrima, labelEn: "Pulcherrima — Forward", labelRu: "Pulcherrima — Прямой" },
  { value: GeminiVoice.Vindemiatrix, labelEn: "Vindemiatrix — Gentle", labelRu: "Vindemiatrix — Мягкий" },
  { value: GeminiVoice.Sulafat, labelEn: "Sulafat — Warm", labelRu: "Sulafat — Тёплый" },
];
